apiVersion: v1
kind: Service
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
  labels:
    {{- include "kms-generic-helm-charts.labels" . | nindent 4 }}
    app: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
spec:
  type: {{ .Values.indexer.service.type }}
  ports:
    - port: {{ .Values.indexer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kms-generic-helm-charts.selectorLabels" . | nindent 4 }}
    {{- with .Values.indexer.podLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    app: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
