name: Release Charts

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add version to Chart.yaml files
        run: |
          VERSION=$(git describe --tags | sed 's/^v//')
          sed -i "s/version: \"0.0.0-dev\"/version: \"$VERSION\"/g" "Chart.yaml"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm charts
        run: |
          helm dependency update
          helm package ${{ github.workspace }} -d .charts-packages/

      - name: Push Charts to GHCR
        run: |
          OCI_REPO="${{ github.repository_owner }}"
          OCI_REPO="${OCI_REPO,,}"
          for pkg in .charts-packages/*; do
            helm push "${pkg}" "oci://ghcr.io/${OCI_REPO}/charts"
          done
