apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
  labels:
    {{- include "kms-generic-helm-charts.labels" . | nindent 4 }}

data:
{{- if .Values.kms_generic.elasticsearch.url }}
  ELASTICSEARCH_URL : {{ .Values.kms_generic.elasticsearch.url }}
{{- else }}
  ELASTICSEARCH_URL : "http://{{ .Release.Name }}-elasticsearch:9200"
{{- end }}
  ELASTICSEARCH_USERNAME : {{ .Values.elasticsearch.security.elasticUsername | default "elastic" | quote }}
  ELASTICSEARCH_PASSWORD : {{ .Values.elasticsearch.security.elasticPassword | default "elastic" | quote}}
  GITHUB_API_TOKEN: {{ .Values.indexer.security.github_api_token | quote }}
  KAGGLE_USERNAME: {{ .Values.indexer.security.kaggle_username | quote }}
  KAGGLE_KEY: {{ .Values.indexer.security.kaggle_key| quote }}
  ACCESS_TOKEN_Gitlab: ""
  GITHUB_QUERY_URL: {{ .Values.kms_generic.github_query_url | default "https://api.github.com/search/code?l=Jupyter+Notebook&q=ipynb+in:path+extension:ipynb" }}
  KMS_ADMIN_USERNAME:  {{ .Values.kms_generic.security.kms_admin | default "kms_admin" | quote }}
  KMS_ADMIN_PASSWORD:  {{ .Values.kms_generic.security.kms_password | default "kms_password" | quote}}
{{- if .Values.kms_generic.postgresql.hostname }}
  POSTGRES_HOSTNAME : {{ .Values.kms_generic.postgresql.hostname }}
  POSTGRES_PORT : {{ .Values.kms_generic.postgresql.port | default "5432" | quote }}
  POSTGRES_USER : {{ .Values.kms_generic.postgresql.auth.username | default "kms_db_user" | quote }}
  POSTGRES_DB : {{ .Values.kms_generic.postgresql.database | default "kms_db" | quote }}
  POSTGRES_PASSWORD: {{ .Values.kms_generic.postgresql.auth.password | default "kms_db" | quote }}
{{- else }}
  POSTGRES_HOSTNAME : {{ .Release.Name }}-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_USER : "kms_db_user"
  POSTGRES_DB : "kms_db"
  POSTGRES_PASSWORD: "kms_db"
{{- end }}
  BASE_PATH: {{ .Values.kms_generic.base_path | quote }}
  DEBUG: {{ .Values.kms_generic.debug | default false | quote }}
  SECRET_KEY: {{ .Values.kms_generic.security.secret_key | quote }}
  ALLOWED_HOSTS: {{ .Values.kms_generic.security.allowed_hosts | quote }}
  CSRF_TRUSTED_ORIGINS: {{ .Values.kms_generic.security.csrf_trusted_origins | quote }}
