apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: index-service
  name: index-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    io.kompose.service: index-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: index-service
  name: index-service
spec:
  selector:
    matchLabels:
      io.kompose.service: index-service
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: index-service
    spec:
      serviceAccountName: index-api
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://mongo:27017
        image: nickipan/indexerservice:latest
        name: index-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: index-api
    namespace: kms
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobs-control
rules:
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status", "cronjobs", "cronjobs/status"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobs-control
subjects:
- kind: ServiceAccount
  name: index-api
  namespace: kms
roleRef:
  kind: ClusterRole
  name: jobs-control
  apiGroup: rbac.authorization.k8s.io