apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
  labels:
    {{- include "kms-generic-helm-charts.labels" . | nindent 4 }}
    app: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
  
spec:
  {{- if not .Values.indexer.autoscaling.enabled }}
  replicas: {{ .Values.indexer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kms-generic-helm-charts.selectorLabels" . | nindent 6 }}
      app: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
  template:
    metadata:
      {{- with .Values.indexer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kms-generic-helm-charts.selectorLabels" . | nindent 8 }}
        {{- with .Values.indexer.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "kms-generic-helm-charts.fullname" . }}-indexer
    spec:
      {{- with .Values.indexer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kms-generic-helm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.indexer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-indexer
          securityContext:
            {{- toYaml .Values.indexer.securityContext | nindent 12 }}
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_URL
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_PASSWORD
            - name: KAGGLE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: KAGGLE_USERNAME
            - name: KAGGLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: KAGGLE_KEY
            - name: GITHUB_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: GITHUB_API_TOKEN

            - name: DATA_DIR
              value: "/app/data"

          volumeMounts:
          - name: indexer-data-storage
            mountPath: /app/data
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}

      volumes:
        - name: indexer-data-storage
        {{- if .Values.indexer.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "indexer.pvc" . }}
        {{- else }}
          emptyDir: {}
        {{ end }}

      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
