apiVersion: v1
kind: Service
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}
  labels:
    {{- include "kms-generic-helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kms_generic.service.type }}
  ports:
    - port: {{ .Values.kms_generic.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kms-generic-helm-charts.selectorLabels" . | nindent 4 }}
    {{- with .Values.kms_generic.podLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
